c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2019                     # [win and x86_64]
c_compiler_version:            # [unix]
  - 13                         # [linux]
  - 18                         # [osx]

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win and x86_64]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]

boost:
  - 1.86.0
lemon:
  - 1.3.1
python:
  - 3.9
  - 3.10
  - 3.11
