package:
    name: dpct
  
    {% set tagged_version = GIT_DESCRIBE_TAG %}

    # If we're using a non-tagged revision, append '.postN' to the version
    {% if GIT_DESCRIBE_NUMBER|int != 0 %}
      {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
    {% endif %}

    version: {{tagged_version}}

source:
    path: ../

build:
  number: 0
  string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - cmake
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - boost {{ boost }} # [py3k]
    - lemon
    - python {{ python }}
  run:
    - boost  # [py3k]
    - lemon
    - python

test:
  source_files:
    - test

  imports:
    - dpct

about:
    home: https://github.com/chaubold/dpct
    license: MIT
    summary: 'Dynamic Programming Cell Tracking Solver Library'
