schema_version: 1

context:
  version: 1.4.0
  lemon: ${{ lemon }}

source:
  path: ..

outputs:
  - package:
      name: dpct-core
      version: ${{ version }}

    build:
      number: 0
      script:
        - if: not win
          then: ${RECIPE_DIR}/build.sh
          else: "%RECIPE_DIR%\\bld.bat"

    requirements:
      build:
        - cmake
        - if: not win
          then:
            - make
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
      host:
        - pybind11
        - lemon ${{ lemon }}*
      run_exports:
        weak:
          - ${{ pin_subpackage("dpct-core", exact=True) }}

    tests:
      - script:
          - echo 1

  - package:
      name: dpct
      version: ${{ version }}

    build:
      number: 0
      script:
        - if: not win
          then: ${RECIPE_DIR}/build-python.sh
          else: "%RECIPE_DIR%\\bld-python.bat"

    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - python
            - cython
        - cmake
        - if: not win
          then:
            - make
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
      host:
        - pybind11
        - lemon ${{ lemon }}*
        - python
        - ${{ pin_subpackage("dpct-core", exact=True) }}
      run:
        - python
        - ${{ pin_subpackage("dpct-core", upper_bound="x.x") }}

    tests:
      - script:
          - python test/test.py
        files:
          source:
            - test/*.py
            - test/*.json

      - python:
          imports:
            - dpct
          pip_check: false

about:
  homepage: https://github.com/chaubold/dpct
  license: MIT
  summary: Dynamic Programming Cell Tracking Solver Library
